/*
 * Copyright (c) 2023 hpmicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by VSCode plugin: HPM Pinmux Tool, version: 0.2.14.
 * Generated Time: 2023/12/30 06:40:11
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H
#ifdef __cplusplus
extern "C" {
#endif

void init_pins(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */